In [9]:
from numpy import array , dot , random
from random import choice

import numpy as np

In [6]:
# McNeuron for AND

w = random.rand(2)

w[0] = 1
w[1] = 1

training_data = [
    (array([0,0]), 0),
    (array([0,1]) , 0),
    (array([1,0]), 0),
    (array([1,1]), 1)
]

step_function  = lambda x : 0 if x < 2 else 1

In [5]:
for x,_ in training_data:
    result = dot(x,w)

    print("{}: {} -> {}".format(x[:2], result, step_function(result)))

[0 0]: 0.0 -> 0
[0 1]: 1.0 -> 0
[1 0]: 1.0 -> 0
[1 1]: 2.0 -> 1


In [7]:
# McNeuron for OR

w = random.rand(2)

w[0] = 1
w[1] = 1

training_data = [
    (array([0,0]), 0),
    (array([0,1]) , 1),
    (array([1,0]), 1),
    (array([1,1]), 1)
]

step_function  = lambda x : 0 if x < 1 else 1

In [8]:
for x,_ in training_data:
    result = dot(x,w)

    print("{}: {} -> {}".format(x[:2], result, step_function(result)))

[0 0]: 0.0 -> 0
[0 1]: 1.0 -> 1
[1 0]: 1.0 -> 1
[1 1]: 2.0 -> 1


RosenBlatt Perception for Boolean Gates, y = W1X1 + W2X2 + W3X3 + b

In [10]:
# RosenBlatt for AND

w = random.rand(3)
b = .1
errors = []
learning_rate = 0.1
no_of_iteration = 1000


training_data = [
    (array([0,0,1]), 0),
    (array([0,1,1]) , 0),
    (array([1,0,1]), 0),
    (array([1,1,1]), 1)
]

step_function  = lambda x : 0 if x < 30 else 1

In [11]:
for i in range(no_of_iteration):
    x, expected = choice(training_data)

    result = dot(w , x)
    error = expected - step_function(result)

    errors.append(error)

    w += learning_rate * error * x

In [13]:
for x,_ in training_data:
    result = dot(x,w)

    print("{}: {} -> {}".format(x[:3], result, step_function(result)))

[0 0 1]: 9.930848534546762 -> 0
[0 1 1]: 20.342934593649616 -> 0
[1 0 1]: 19.67338866294385 -> 0
[1 1 1]: 30.085474722046705 -> 1
